Indentation

diff --git a/actions/push-to-gar-docker-multi-arch/action.yaml b/actions/push-to-gar-docker-multi-arch/action.yaml
--- a/actions/push-to-gar-docker-multi-arch/action.yaml
+++ b/actions/push-to-gar-docker-multi-arch/action.yaml
@@ -7,72 +7,68 @@ on:
         type: string
         description: desc
         required: true
-# outputs:
-#   resolved_platforms: 
-#     description: resolved-platform
-#     value: ${{ steps.print.outputs.processed-platforms }}
 
 jobs:
   build-multi-arch-job:
-  strategy:
-    matrix:
-      os: ${{ inputs.platforms }}
-  runs-on: ubuntu-${{ matrix.os }}-large
-  permissions:
-    contents: "read"
-    id-token: "write"
-  steps:
-    - name: Checkout
-      env:
-        action_repo: ${{ github.action_repository }}
-        action_ref: ${{ github.action_ref }}
-      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-      with:
-        repository: ${{ env.action_repo }}
-        ref: ${{ env.action_ref }}
-        path: shared-workflows
-    - name: Get repository name
-      id: get-repository-name
-      shell: bash
-      run: |
-        REPO_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $2}')
-        echo "repo_name=${REPO_NAME}" >> ${GITHUB_OUTPUT}
-    - name: Resolve GCP project
-      id: resolve-project
-      shell: bash
-      run: |
-        if [ "${{ inputs.environment }}" == 'dev' ]; then
-          PROJECT="grafanalabs-dev"
-        elif [ "${{ inputs.environment }}" == 'prod' ]; then
-          PROJECT="grafanalabs-global"
-        else
-          echo "Invalid environment. Valid environment variable inputs: dev, prod"
-          exit 1
-        fi
-        echo "project=${PROJECT}" >> ${GITHUB_OUTPUT}
-    - name: Login to GAR
-      uses: ./shared-workflows/actions/login-to-gar
-      with:
-        environment: ${{ inputs.environment }}
-    - name: Extract metadata (tags, labels) for Docker
-      id: meta
-      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
-      with:
-        images: "${{ inputs.registry }}/${{ steps.resolve-project.outputs.project }}/docker-${{ steps.get-repository-name.outputs.repo_name }}-${{ inputs.environment }}/${{ inputs.image_name }}"
-        tags: ${{ inputs.tags }}
-        create_credentials_file: false
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
-    - name: Build the container
-      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
-      id: build
-      with:
-        context: ${{ inputs.context }}
-        build-args: ${{ inputs.build-args }}
-        push: ${{ github.event_name == 'push' }}
-        tags: ${{ steps.meta.outputs.tags }}
-        cache-from: ${{ inputs.cache-from }}
-        cache-to: ${{ inputs.cache-to }}
-        file: ${{ inputs.file }}
-        platforms: ${{ inputs.platforms }}
-        ssh: ${{ inputs.ssh }}
+    strategy:
+      matrix:
+        os: ${{ inputs.platforms }}
+    runs-on: ubuntu-${{ matrix.os }}-large
+    permissions:
+      contents: "read"
+      id-token: "write"
+    steps:
+      - name: Checkout
+        env:
+          action_repo: ${{ github.action_repository }}
+          action_ref: ${{ github.action_ref }}
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        with:
+          repository: ${{ env.action_repo }}
+          ref: ${{ env.action_ref }}
+          path: shared-workflows
+      - name: Get repository name
+        id: get-repository-name
+        shell: bash
+        run: |
+          REPO_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $2}')
+          echo "repo_name=${REPO_NAME}" >> ${GITHUB_OUTPUT}
+      - name: Resolve GCP project
+        id: resolve-project
+        shell: bash
+        run: |
+          if [ "${{ inputs.environment }}" == 'dev' ]; then
+            PROJECT="grafanalabs-dev"
+          elif [ "${{ inputs.environment }}" == 'prod' ]; then
+            PROJECT="grafanalabs-global"
+          else
+            echo "Invalid environment. Valid environment variable inputs: dev, prod"
+            exit 1
+          fi
+          echo "project=${PROJECT}" >> ${GITHUB_OUTPUT}
+      - name: Login to GAR
+        uses: ./shared-workflows/actions/login-to-gar
+        with:
+          environment: ${{ inputs.environment }}
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
+        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
+        with:
+          images: "${{ inputs.registry }}/${{ steps.resolve-project.outputs.project }}/docker-${{ steps.get-repository-name.outputs.repo_name }}-${{ inputs.environment }}/${{ inputs.image_name }}"
+          tags: ${{ inputs.tags }}
+          create_credentials_file: false
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
+      - name: Build the container
+        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
+        id: build
+        with:
+          context: ${{ inputs.context }}
+          build-args: ${{ inputs.build-args }}
+          push: ${{ github.event_name == 'push' }}
+          tags: ${{ steps.meta.outputs.tags }}
+          cache-from: ${{ inputs.cache-from }}
+          cache-to: ${{ inputs.cache-to }}
+          file: ${{ inputs.file }}
+          platforms: ${{ inputs.platforms }}
+          ssh: ${{ inputs.ssh }}
